import { useState } from 'react'
import axios from 'axios'

export default function CaseIntelligence() {
  const [caseId, setCaseId] = useState('')
  const [data, setData] = useState<any>(null)
  const [note, setNote] = useState('')
  const [assignee, setAssignee] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const load = async (id = caseId) => { if (!id) return; setLoading(true); setError(''); try { setData((await axios.get(`/api/investigator/complaint/${id}/intelligence`)).data) } catch (e: any) { setError(e.response?.data?.detail || 'Unable to load case intelligence') } finally { setLoading(false) } }
  const addNote = async () => { if (!note.trim() || !caseId) return; await axios.post(`/api/investigator/complaint/${caseId}/notes`, { body: note, assignee: assignee || undefined }); setNote(''); setAssignee(''); await load() }
  return <div className="portal-shell"><div className="portal-page max-w-6xl mx-auto space-y-6">
    <header><p className="portal-eyebrow">Investigator / AI intelligence</p><h1 className="portal-title mt-2">Case intelligence workspace</h1><p className="portal-muted mt-2">Explainable links, prioritization, recovery guidance, evidence context, and collaboration for a selected case.</p></header>
    <div className="portal-panel p-5 flex gap-3"><input className="field flex-1" value={caseId} onChange={e => setCaseId(e.target.value)} placeholder="Enter internal complaint ID (e.g. 12)" /><button onClick={() => load()} className="rounded-xl bg-cyan-500 px-5 font-extrabold text-slate-950">{loading ? 'Loading…' : 'Analyze case'}</button></div>
    {error && <p className="rounded-xl border border-red-500/30 bg-red-950/30 p-4 text-red-200">{error}</p>}
    {data && <>
      <section className="grid md:grid-cols-3 gap-4"><Card title="Investigation priority" value={`${data.priority.level} · ${data.priority.score}/100`} accent={data.priority.level === 'Critical' ? 'text-rose-300' : 'text-amber-300'} items={data.priority.reasons} /><Card title="Recovery probability" value={`${data.recovery.score}%`} accent="text-emerald-300" items={[data.recovery.recommendation]} /><Card title="Fraud network" value={data.network.campaign_detected ? 'Campaign signal detected' : 'No campaign signal'} accent="text-purple-300" items={[`${data.network.victim_count} connected victim(s)`, `${data.network.linked_cases.length} linked case(s)`]} /></section>
      <section className="grid lg:grid-cols-2 gap-5"><Panel title="Next best actions" items={data.next_actions} /><Panel title="Investigation playbook" items={data.playbook} /></section>
      <section className="grid lg:grid-cols-2 gap-5"><div className="portal-panel p-5"><h2 className="font-bold text-white">🕸️ Link analysis & suspect profile</h2><p className="text-sm text-slate-400 mt-1">{data.suspect_profile.linked_complaints} linked reports · estimated linked loss ₹{Number(data.suspect_profile.estimated_loss || 0).toLocaleString('en-IN')}</p><div className="mt-4 flex flex-wrap gap-2">{Object.entries(data.network.indicators).flatMap(([kind, values]: any) => values.map((value: string) => <span key={`${kind}-${value}`} className="rounded-lg bg-purple-950/50 border border-purple-500/30 px-2.5 py-1 text-xs text-purple-200">{kind}: {value}</span>))}</div><div className="mt-4 space-y-2">{data.network.linked_cases.length ? data.network.linked_cases.map((item: any) => <div key={item.id} className="rounded-lg bg-slate-950 p-3 text-sm"><b>{item.tracking_id || `#${item.id}`}</b> · {item.title} <span className="text-cyan-300">{item.match}% match</span><p className="text-xs text-slate-500 mt-1">Shared: {item.shared_indicators.join(', ') || 'similar narrative'}</p></div>) : <p className="text-sm text-slate-500">No matching indicators found in other reports.</p>}</div></div><div className="portal-panel p-5"><h2 className="font-bold text-white">📡 Live threat intelligence (local ledger)</h2><p className="text-xs text-slate-400 mt-1">Indicator prevalence across submitted reports.</p><div className="mt-4 space-y-2">{data.threat_intelligence.length ? data.threat_intelligence.map((item: any) => <div key={`${item.type}-${item.indicator}`} className="flex justify-between rounded-lg bg-slate-950 p-3 text-sm"><span className="font-mono text-slate-200">{item.indicator}</span><span className="text-amber-300">Reported {item.reports}×</span></div>) : <p className="text-sm text-slate-500">No extractable threat indicators recorded.</p>}</div></div></section>
      <section className="portal-panel p-5"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><h2 className="font-bold text-white">💸 Reported financial flow</h2><p className="mt-1 text-xs text-slate-400">A case-derived lead, not verified transaction tracing.</p></div>{data.financial_flow.reported_amount ? <b className="text-amber-300">₹{Number(data.financial_flow.reported_amount).toLocaleString('en-IN')} reported</b> : null}</div>{data.financial_flow.available ? <><div className="mt-5 flex flex-wrap items-center gap-2">{data.financial_flow.nodes.map((node: any, index: number) => <div key={`${node.type}-${node.label}`} className="flex items-center gap-2">{index > 0 && <span className="text-cyan-400">→</span>}<div className={`rounded-lg border px-3 py-2 text-sm ${node.type === 'source' ? 'border-cyan-500/30 bg-cyan-950/30 text-cyan-100' : 'border-amber-500/30 bg-amber-950/30 text-amber-100'}`}><p className="text-[10px] uppercase text-slate-400">{node.title || node.type}</p><p className="font-mono break-all">{node.label}</p></div></div>)}</div><p className="mt-4 text-xs text-slate-500">{data.financial_flow.assessment}</p></> : <p className="mt-4 text-sm text-slate-500">{data.financial_flow.assessment}</p>}</section>
      <section className="grid lg:grid-cols-2 gap-5"><Panel title="Scam timeline reconstruction" items={data.timeline.map((item: any) => `${item.time ? new Date(item.time).toLocaleString() : 'Reported'} — ${item.event}`)} /><Panel title="Similar solved cases" items={data.similar_solved_cases.length ? data.similar_solved_cases.map((item: any) => `${item.tracking_id || `#${item.id}`} · ${item.match}% match · ${item.title}`) : ['No resolved case with a strong pattern match yet.']} /></section>
      <section className="grid lg:grid-cols-2 gap-5"><Panel title="AI evidence summary" items={data.evidence_summary.length ? data.evidence_summary.map((item: any) => `${item.filename} — ${item.summary}`) : ['No evidence files attached.']} /><Panel title="Digital chain of custody" items={data.chain_of_custody.map((item: any) => `${item.time ? new Date(item.time).toLocaleString() : ''} — ${item.action} by ${item.actor}`)} /></section>
      <section className="portal-panel p-5"><h2 className="font-bold text-white">🤝 Investigation collaboration</h2><div className="mt-4 grid md:grid-cols-[1fr_180px_auto] gap-2"><input className="field" value={note} onChange={e => setNote(e.target.value)} placeholder="Add a case note or task; use @Officer Name for mentions" /><input className="field" value={assignee} onChange={e => setAssignee(e.target.value)} placeholder="Assign to" /><button onClick={addNote} className="rounded-lg bg-violet-600 px-4 font-bold">Add note</button></div><div className="mt-4 space-y-2">{data.notes.length ? data.notes.map((item: any) => <div key={item.id} className="rounded-lg bg-slate-950 p-3 text-sm"><b>{item.author}</b>{item.assignee && <span className="text-cyan-300"> → {item.assignee}</span>}<p className="mt-1 text-slate-300">{item.body}</p></div>) : <p className="text-sm text-slate-500">No collaboration notes yet.</p>}</div></section>
    </>}
  </div></div>
}
function Card({ title, value, accent, items }: { title: string; value: string; accent: string; items: string[] }) { return <div className="kpi-card"><p className="text-xs uppercase tracking-wide text-slate-400">{title}</p><p className={`mt-3 text-xl font-extrabold ${accent}`}>{value}</p><div className="mt-3 text-xs text-slate-400 space-y-1">{items.map(item => <p key={item}>• {item}</p>)}</div></div> }
function Panel({ title, items }: { title: string; items: string[] }) { return <div className="portal-panel p-5"><h2 className="font-bold text-white">{title}</h2><div className="mt-3 space-y-2">{items.map((item, index) => <p key={`${item}-${index}`} className="rounded-lg bg-slate-950 p-3 text-sm text-slate-300">{index + 1}. {item}</p>)}</div></div> }
