import { useEffect, useState } from 'react'
import axios from 'axios'

export default function Governance() {
  const [data, setData] = useState<any>(null)
  const [logs, setLogs] = useState<any[]>([])
  const [loginHistory, setLoginHistory] = useState<any[]>([])
  const [message, setMessage] = useState('')
  const load = () => Promise.all([axios.get('/api/admin/governance'), axios.get('/api/admin/audit-logs'), axios.get('/api/auth/login-history')]).then(([overview, audit, history]) => { setData(overview.data); setLogs(audit.data); setLoginHistory(history.data) }).catch(() => setMessage('Unable to load governance data.'))
  useEffect(() => { void load() }, [])
  const exportCsv = async () => { const result = await axios.get('/api/admin/export/complaints', { responseType: 'blob' }); const url = URL.createObjectURL(result.data); const link = document.createElement('a'); link.href = url; link.download = 'cybershield-complaints.csv'; link.click(); URL.revokeObjectURL(url) }
  const backup = async () => { const result = await axios.post('/api/admin/backups'); setMessage(`Backup created: ${result.data.filename}`) }
  if (!data) return <div className="portal-shell"><div className="portal-page text-slate-400">Loading system governance…</div></div>
  const metrics = [['Registered users', data.users.total], ['Citizens', data.users.citizens], ['Investigators', data.users.investigators], ['Pending approvals', data.users.pending_investigators], ['Total complaints', data.cases.total], ['Active investigations', data.cases.active], ['High-risk cases', data.cases.high_risk], ['Resolved cases', data.cases.resolved]]
  return <div className="portal-shell"><div className="portal-page max-w-6xl mx-auto space-y-6"><header className="flex flex-col md:flex-row justify-between gap-4"><div><p className="portal-eyebrow">Administration / Governance & security</p><h1 className="portal-title mt-2">System governance center</h1><p className="portal-muted mt-2">Monitor platform health, security activity, compliance signals, evidence storage, and operational statistics.</p></div><div className="flex gap-2"><button onClick={exportCsv} className="rounded-lg border border-slate-600 px-4 py-2 text-sm font-bold">Export CSV</button><button onClick={backup} className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-extrabold text-slate-950">Create backup</button></div></header>{message && <p className="rounded-lg bg-cyan-950 p-3 text-sm text-cyan-200">{message}</p>}
    <section className="grid grid-cols-2 md:grid-cols-4 gap-3">{metrics.map(([label, value]) => <div key={label as string} className="kpi-card"><p className="text-xs text-slate-400 uppercase">{label}</p><p className="mt-3 text-2xl font-extrabold text-white">{value}</p></div>)}</section>
    <section className="grid lg:grid-cols-2 gap-5"><div className="portal-panel p-5"><h2 className="font-bold text-white">System health overview</h2><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(data.system).map(([name, value]: any) => <div key={name} className="rounded-lg bg-slate-950 p-3"><p className="text-xs text-slate-500 capitalize">{name.replace('_', ' ')}</p><p className={`mt-1 text-sm font-bold ${String(value).includes('online') || String(value).includes('configured') ? 'text-emerald-300' : 'text-amber-300'}`}>{String(value)}</p></div>)}</div></div><div className="portal-panel p-5"><h2 className="font-bold text-white">Evidence storage & compliance</h2><div className="mt-4 space-y-3 text-sm"><Line label="Encrypted evidence files" value={data.evidence.encrypted_files} /><Line label="Storage used" value={`${(data.evidence.storage_bytes / 1024).toFixed(1)} KB`} /><Line label="Hash verification success" value={`${data.evidence.hash_success_rate}%`} /><Line label="Tampered-evidence alerts" value={data.evidence.tamper_alerts} /><Line label="Resolution rate" value={`${data.cases.resolution_rate}%`} /><Line label="Average resolution" value={data.cases.avg_resolution_days ? `${data.cases.avg_resolution_days} days` : 'No resolved cases'} /><Line label="Average reported loss" value={`₹${Number(data.cases.avg_financial_loss).toLocaleString('en-IN')}`} /></div></div></section>
    <section className="grid lg:grid-cols-2 gap-5"><div className="portal-panel p-5"><h2 className="font-bold text-white">Notification center</h2><div className="mt-4 space-y-2">{data.notifications.length ? data.notifications.map((item: any, i: number) => <div key={i} className={`rounded-lg p-3 text-sm ${item.severity === 'critical' ? 'bg-red-950/40 text-red-200' : item.severity === 'high' ? 'bg-amber-950/40 text-amber-200' : 'bg-cyan-950/40 text-cyan-200'}`}><b className="uppercase text-xs">{item.severity}</b><p>{item.message}</p></div>) : <p className="text-sm text-slate-500">No current governance alerts.</p>}</div></div><div className="portal-panel p-5"><h2 className="font-bold text-white">Configuration & access controls</h2><p className="mt-3 text-sm text-slate-400">Role protection is active for citizen, investigator, and administrator routes. Use User Management to review account status and the Settings screen to configure policy controls.</p><a href="/admin/settings" className="inline-block mt-4 text-sm font-bold text-cyan-300">Open configuration →</a></div></section>
    <section className="portal-panel overflow-hidden"><div className="p-5 border-b border-slate-700"><h2 className="font-bold text-white">Your recent sign-ins</h2><p className="text-xs text-slate-400 mt-1">A private security record for the current administrator account.</p></div><div className="divide-y divide-slate-800">{loginHistory.length ? loginHistory.map((item, i) => <div key={`${item.created_at}-${i}`} className="p-4 text-sm flex flex-col sm:flex-row gap-1 sm:gap-4"><span className="text-slate-500 sm:w-48 shrink-0">{new Date(item.created_at).toLocaleString()}</span><span className="text-slate-200">{item.ip_address || 'IP unavailable'}</span><span className="truncate text-slate-500">{item.user_agent || 'User agent unavailable'}</span></div>) : <p className="p-4 text-sm text-slate-500">No sign-in history has been recorded yet.</p>}</div></section>
    <section className="portal-panel overflow-hidden"><div className="p-5 border-b border-slate-700"><h2 className="font-bold text-white">Security & audit logs</h2><p className="text-xs text-slate-400 mt-1">Complaint actions, evidence access, status changes, approvals, and login events.</p></div><div className="max-h-96 overflow-auto divide-y divide-slate-800">{logs.map(item => <div key={item.id} className="p-4 text-sm flex gap-4"><span className="text-slate-500 w-40 shrink-0">{item.timestamp ? new Date(item.timestamp).toLocaleString() : '—'}</span><div><b className="text-white">{item.action}</b><span className="text-cyan-300"> · {item.actor}</span><p className="text-slate-500 mt-1">{item.details || (item.complaint_id ? `Case #${item.complaint_id}` : 'System activity')}</p></div></div>)}</div></section>
  </div></div>
}
function Line({ label, value }: { label: string; value: string | number }) { return <div className="flex justify-between rounded-lg bg-slate-950 px-3 py-2"><span className="text-slate-400">{label}</span><b className="text-slate-100">{value}</b></div> }
