import { useEffect, useState } from 'react'
import axios from 'axios'

export default function Operations() {
  const [performance, setPerformance] = useState<any[]>([])
  const [requests, setRequests] = useState<any[]>([])
  const [caseId, setCaseId] = useState('')
  const [agency, setAgency] = useState('Bank Fraud Cell')
  const [requestType, setRequestType] = useState('Bank freeze request')
  const [message, setMessage] = useState('')
  const [draft, setDraft] = useState('')
  const refresh = () => Promise.all([axios.get('/api/admin/performance'), axios.get('/api/admin/agency-requests')]).then(([p, r]) => { setPerformance(p.data); setRequests(r.data) }).catch(() => undefined)
  useEffect(() => { void refresh() }, [])
  const createRequest = async () => { if (!caseId || !message) return; await axios.post('/api/admin/agency-requests', { complaint_id: Number(caseId), agency, request_type: requestType, message }); setMessage(''); await refresh() }
  const createDraft = async (kind: string) => { if (!caseId) return; const response = await axios.get(`/api/admin/legal-drafts/${caseId}`, { params: { kind } }); setDraft(response.data.draft) }
  return <div className="portal-shell"><div className="portal-page max-w-6xl mx-auto space-y-6"><header><p className="portal-eyebrow">Administration / Operations</p><h1 className="portal-title mt-2">Agency coordination & legal drafting</h1><p className="portal-muted mt-2">Prepare auditable agency requests, review officer performance, and generate officer-reviewed case drafts.</p></header>
    <section className="portal-panel p-5"><h2 className="font-bold text-white">Investigator performance dashboard</h2><div className="mt-4 grid md:grid-cols-3 gap-3">{performance.length ? performance.map(item => <div key={item.name} className="rounded-xl bg-slate-950 p-4"><p className="font-bold">{item.name}</p><p className="mt-2 text-sm text-slate-400">Assigned: {item.assigned} · Resolved: {item.resolved}</p><p className="text-sm text-cyan-300">Evidence verified: {item.evidence_verified}</p><p className="text-xs text-slate-500 mt-1">Avg. resolution: {item.avg_resolution_days ?? '—'} days</p></div>) : <p className="text-sm text-slate-500">No approved investigators or assignment data yet.</p>}</div></section>
    <section className="grid lg:grid-cols-2 gap-5"><div className="portal-panel p-5 space-y-3"><h2 className="font-bold text-white">Secure agency communication hub</h2><input className="field" value={caseId} onChange={e => setCaseId(e.target.value)} placeholder="Internal complaint ID" /><select className="field" value={agency} onChange={e => setAgency(e.target.value)}><option>Bank Fraud Cell</option><option>Telecom Operator</option><option>Payment Gateway</option><option>Cryptocurrency Exchange</option><option>CERT-In</option></select><select className="field" value={requestType} onChange={e => setRequestType(e.target.value)}><option>Bank freeze request</option><option>KYC information request</option><option>Telecom subscriber request</option><option>Indicator takedown request</option></select><textarea className="field min-h-28" value={message} onChange={e => setMessage(e.target.value)} placeholder="Write the officer-reviewed request message…" /><button onClick={createRequest} className="rounded-lg bg-amber-600 px-4 py-2 font-bold">Save agency request draft</button><p className="text-xs text-slate-500">Drafts are audited locally. Configure a secure agency delivery integration before sending externally.</p></div><div className="portal-panel p-5"><h2 className="font-bold text-white">Automated legal drafts</h2><p className="text-sm text-slate-400 mt-1">Enter the case ID at left, then create a review draft.</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => createDraft('bank_freeze')} className="rounded-lg bg-violet-700 px-3 py-2 text-sm font-bold">Bank freeze request</button><button onClick={() => createDraft('fir_summary')} className="rounded-lg bg-violet-700 px-3 py-2 text-sm font-bold">FIR summary</button><button onClick={() => createDraft('evidence_report')} className="rounded-lg bg-violet-700 px-3 py-2 text-sm font-bold">Evidence report</button></div>{draft && <textarea readOnly className="field mt-4 min-h-64 text-sm" value={draft} />}</div></section>
    <section className="portal-panel overflow-hidden"><div className="p-5 border-b border-slate-700"><h2 className="font-bold text-white">Recent coordination drafts</h2></div>{requests.length ? <div className="divide-y divide-slate-800">{requests.map(item => <div key={item.id} className="p-4 flex justify-between gap-4 text-sm"><div><b>Case #{item.complaint_id}</b> · {item.request_type}<p className="text-slate-400 mt-1">{item.agency} · by {item.created_by}</p></div><span className="status-pill bg-amber-500/10 text-amber-300">{item.status}</span></div>)}</div> : <p className="p-5 text-sm text-slate-500">No agency requests drafted yet.</p>}</section>
  </div></div>
}
