import { useEffect, useState } from 'react'
import axios from 'axios'

const defaults = { autoAssignAgency: true, requireBlockchainVerification: false, aiAutoClassify: true, notifyOnHighRisk: true, duplicateDetectionThreshold: 80, maxEvidenceSize: 10, retentionDays: 365, autoResolveDays: 30 }
type Settings = typeof defaults

export default function AdminSettings() {
  const [settings, setSettings] = useState<Settings>(defaults)
  const [status, setStatus] = useState('')
  useEffect(() => { axios.get('/api/admin/settings').then(r => setSettings(r.data)).catch(() => setStatus('Unable to load saved settings.')) }, [])
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings(current => ({ ...current, [key]: value }))
  const save = async () => { setStatus('Saving…'); try { const response = await axios.put('/api/admin/settings', settings); setSettings(response.data); setStatus('Settings saved and audit logged.'); } catch { setStatus('Settings could not be saved.'); } }
  return <div className="portal-shell"><div className="portal-page max-w-5xl space-y-5"><header><p className="portal-eyebrow">Administration / Configuration</p><h1 className="portal-title mt-2">Platform settings</h1><p className="portal-muted mt-2">Control intake automation, evidence policy, alerts, and data lifecycle. Changes are stored centrally.</p></header>
    <section className="grid lg:grid-cols-2 gap-5"><Panel title="Automation & alerts"> <Toggle label="Auto-assign agency" text="Route cases based on detected crime type." value={settings.autoAssignAgency} onChange={v => update('autoAssignAgency', v)} /><Toggle label="AI auto-classification" text="Analyze each submitted complaint at intake." value={settings.aiAutoClassify} onChange={v => update('aiAutoClassify', v)} /><Toggle label="High-risk notifications" text="Notify administrators when risk exceeds 70." value={settings.notifyOnHighRisk} onChange={v => update('notifyOnHighRisk', v)} /></Panel>
      <Panel title="Evidence & integrity"><Toggle label="Require blockchain anchoring" text="Require optional chain anchor before evidence is marked anchored." value={settings.requireBlockchainVerification} onChange={v => update('requireBlockchainVerification', v)} /><NumberField label="Maximum evidence upload (MB)" value={settings.maxEvidenceSize} min={1} max={100} onChange={v => update('maxEvidenceSize', v)} /><NumberField label="Duplicate-match threshold (%)" value={settings.duplicateDetectionThreshold} min={50} max={100} onChange={v => update('duplicateDetectionThreshold', v)} /></Panel>
      <Panel title="Data lifecycle"><NumberField label="Evidence retention (days)" value={settings.retentionDays} min={30} max={3650} onChange={v => update('retentionDays', v)} /><NumberField label="Auto-resolve after (days)" value={settings.autoResolveDays} min={1} max={365} onChange={v => update('autoResolveDays', v)} /><p className="mt-5 rounded-lg border border-amber-500/20 bg-amber-950/20 p-3 text-xs text-amber-200">Retention settings are policy controls. Existing evidence is never deleted automatically.</p></Panel>
      <Panel title="Access policy"><div className="space-y-3 text-sm">{[['Citizen', 'Own reports and tracking'], ['Investigator', 'Casework, threat graph, integrity checks'], ['Administrator', 'Platform policy and operational oversight']].map(([role, rights]) => <div key={role} className="rounded-lg bg-slate-950/60 p-3"><p className="font-semibold text-slate-100">{role}</p><p className="mt-1 text-xs text-slate-400">{rights}</p></div>)}</div></Panel></section>
    <footer className="portal-panel flex items-center justify-between p-4"><p className="text-sm text-slate-400">{status || 'No unsaved changes.'}</p><button onClick={save} className="rounded-lg bg-cyan-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-cyan-500">Save settings</button></footer>
  </div></div>
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="portal-panel p-5"><h2 className="text-sm font-bold text-white">{title}</h2><div className="mt-4 space-y-4">{children}</div></section> }
function Toggle({ label, text, value, onChange }: { label: string; text: string; value: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4"><div><p className="text-sm text-slate-200">{label}</p><p className="text-xs text-slate-500 mt-1">{text}</p></div><button aria-label={label} onClick={() => onChange(!value)} className={`h-6 w-11 rounded-full p-0.5 transition ${value ? 'bg-cyan-500' : 'bg-slate-700'}`}><span className={`block h-5 w-5 rounded-full bg-white transition-transform ${value ? 'translate-x-5' : ''}`} /></button></div> }
function NumberField({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <label className="block text-sm text-slate-200">{label}<input type="number" min={min} max={max} value={value} onChange={e => onChange(Number(e.target.value))} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100 outline-none focus:border-cyan-400" /></label> }
